apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-training-akash
spec:
  selector:
    matchLabels:
      app: gke-training-akash
  replicas: 1
  template:
    metadata:
      labels:
        app: gke-training-akash
    spec:
      containers:
      - name: nodeapp
        image: anm237/gketraining:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
