apiVersion: v1
kind: Service
metadata:
  name: gke-training-akash
spec:
  type: LoadBalancer
  selector:
    app: gke-training-akash
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
