apiVersion: v1
kind: Service
metadata:  
  name: gke-training-akash
spec:
  selector:    
    app: gke-training-akash
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
